### ISSUE TITLE
The forecast APIs being used is deprecated, and results in two HTTP requests

### ISSUE THREAD

**Issue by rewsssiestedbo** [MatthewFlamm/pynws#10]
The /points/{point}/forecast and /points/{point}/forecast/hourly APIs are listed on https://www.weather.gov/documentation/services-web-api as deprecated.  Each of them actually result in returning an HTTP 301 redirect to the /gridpoints/{wfo}/{x},{y}/forecast (.../hourly) endpoints to actually retrieve the forecast data.   The correct forecast and hourly forecast URLs are returned as properties on a call to /points/{point}.  Perhaps you should get the point properties on object creation and save the URLs for use to get the forecast data.

**Comment by MatthewFlamm** [comment]
Thanks.  I don't believe these were deprecated earlier, but either way, I'll look into implementing it.

**Comment by rewsssiestedbo** [comment]
Based on the copies of the page on archive.org, they were changed to deprecated sometime between November 22, 2018 and April 20, 2019.  

Note that the /points/{point}/stations URL also does a redirect to a /gridpoints URL.   If you are picking up the forecast URLs from the /point data, you can also get the /gridpoints URL for getting the station list.
