### ISSUE TITLE
Handling bad rawMessage data.

### ISSUE THREAD

**Issue by rewsssiestedbo** [MatthewFlamm/pynws#13]
There are some stations that will return text in rawMessage that is not a valid METAR message - it looks like the original METAR text gets partially duplicated.  PHTO seems to do this fairly frequently.  As this will result in an exception being generated by the Metar constructor, and therefore update_observation will fail and pass back an exception.  Note that while the cases I have seen with the bad METAR text do not include values for the observations you use in the HA nws weather component, they do contain valid values for other observations.

You should probably catch the Metar.ParserError exception and treat it as if rawMessage was null.

**Comment by MatthewFlamm** [comment]
Good idea on handling non-parseable metar codes.  Right now it only checks if it exists.  I don't think I want to parse partially acceptable Metar data, that isn't in scope of this library.  If the python-metar library implements the ability to distinguish valid from unvalid metar codes, we could utilize it here.  You could consider creating an issue there with an example to request partial metar parsing.

**Comment by rewsssiestedbo** [comment]
If the argument to the Metar constructor is not a valid METAR message, it generates a Metar.ParserError exception.  So the code below from my sensor shows how this can be treated as there being no METAR data:

 metar = None
        if 'rawMessage' in obsprop:
            if obsprop['rawMessage'] is not None:
                #
                # parse the METAR message so that we can use the values
                # if not in individual measurement item.
                #
                try:
                    metar = Metar.Metar(obsprop['rawMessage'])
                except Metar.ParserError:
                    pass

Here is an example of a typical bad value from PHTO:
                "timestamp": "2019-08-05T04:18:00+00:00",
                "rawMessage": "PHTO 050418Z 05007KT 2 1/2SM RA FEW014 BKN039 OVC050 26/22 A2998PHTO 050418Z 05007KT 2 1/2SM RA FEW014 BKN039 OVC050 26/22 A2998 RMK AO2 RAB09 P0000 T02610222",

**Comment by MatthewFlamm** [comment]
Fixed in #14
