### ISSUE TITLE
Unable to create new NWS integration in HA due to possible API change

### ISSUE THREAD

**Issue by lymanepp** [MatthewFlamm/pynws#135]
I'm getting a weird response trying to set up a new NWS integration in HA. The following API call is returning a weird redirect. I don't know if this is a temporary issue or deliberate change on their part.

```
$ curl https://api.weather.gov/points/27,-81/stations
{
    "correlationId": "6a409487",
    "title": "Redirect",
    "type": "https://api.weather.gov/problems/GridpointRedirect",
    "status": 301,
    "detail": "The requested data can be found here: /gridpoints/KEY/130,75/stations",
    "instance": "https://api.weather.gov/requests/6a409487"
}
```

**Comment by lymanepp** [comment]
I reported this to NWS.

**Comment by MatthewFlamm** [comment]
This endpoint is deprecated.  But your link works for me now.  I assume that this endpoint will be flakier then the rest, so we should refactor this part of the code.

**Comment by lymanepp** [comment]
Submitted PR https://github.com/MatthewFlamm/pynws/pull/136 to fix this.

**Comment by lymanepp** [comment]
HA 2023.9.0 is working fine without this change. I think the NWS API had a temporary problem while I was trying to setup a test environment. However, this change is still good because the deprecated endpoint is doing an HTTP redirect to the right endpoint and that redirect could be removed at any time.

Edit: aiohttp must be following HTTP redirects by default or as configured by HA.
