### ISSUE TITLE
Icon format in forecast change

### ISSUE THREAD

**Issue by MatthewFlamm** [MatthewFlamm/pynws#207]
API used to return something like:

```
"icon": "https://api.weather.gov/icons/land/night/sct?size=small",
```

now it returns something like

```
"icon": "/icons/land/night/sct?size=small",
```

**Comment by MatthewFlamm** [comment]
See report in https://github.com/home-assistant/core/issues/119114

**Comment by kevinhaas** [comment]
Thanks for addressing this so quickly!

**Comment by MatthewFlamm** [comment]
Interestingly, as I sort of predicted, my local station is back to the original format of 

```
"icon": "https://api.weather.gov/icons/land/night/sct?size=small",
```

I bet it was an unintentional change, but I will keep an eye on it.  If you have more failures in homeassistant, like if your particular station is still stuck with the 'new' format, please open up a _new_ issue in homeassistant. Then, this will help push the the version update there when I make it.

**Comment by kevinhaas** [comment]
I still see the error but I'll keep an eye on it. Opened a separate issue https://github.com/home-assistant/core/issues/120046
