### ISSUE TITLE
Add UV index

### ISSUE THREAD

**Issue by Sudo-Rob** [MatthewFlamm/pynws#62]
Is it possible to add a UV index entity to the NWS integration? Current index is likely sufficient, but data comes packaged as hourly or daily.  A zip code is required for localization.

Here's info on the API: [https://www.epa.gov/enviro/web-services](url)

**Comment by MatthewFlamm** [comment]
This sounds like an EPA integration to me.  These are separate servers and API endpoints.

**Comment by Sudo-Rob** [comment]
I can't disagree, but the index is seen on a some weather cards.  Other countries include it in their meteorology data.

Respectfully...

**Comment by Sudo-Rob** [comment]
Curiously, this NWS page directs the consumer to the EPA site.

[https://www.weather.gov/ilx/uv-index](https://www.weather.gov/ilx/uv-index)

Unfortunately, the NWS product is a forecast of the next day's index.

[https://www.cpc.ncep.noaa.gov/products/stratosphere/uv_index/uv_current.shtml](https://www.cpc.ncep.noaa.gov/products/stratosphere/uv_index/uv_current.shtml)

**Comment by MatthewFlamm** [comment]
While it makes sense that this data should be together, this library is for the api.waether.gov endpoint. If NWS adds UV index to that data, then I'm 100% for it.

**Comment by Sudo-Rob** [comment]
I understand.  Thanks for the quick response.
