### ISSUE TITLE
Nonmonotonic time tags in daynight datetime[0]

### ISSUE THREAD

**Issue by Sudo-Rob** [MatthewFlamm/pynws#91]
I needed to look at some attributes to understand how they behave over the course of the day.  In doing so, I see unexpected behavior in the attribute daytime[0].  I assume the source is from the API raw data associated with the `StartTime` in `period number: 1`.  This is what I see occur several times a day:

![image](https://user-images.githubusercontent.com/56487711/168652391-f1ab7c83-b54d-4cf7-a59b-b0365fc3e1e9.png)

The observation is there is an occasional reversal of the time tag state to the preceding hour.  I realize the origin is likely the NWS data, but would like to first confirm it is in the raw date rather the the NWS integration.  If I should move the issue to home-assistant/core, just say the word.

**Comment by MatthewFlamm** [comment]
This should be straight from NWS servers.  This could be related to the (hopefully) mostly fixed cached "old-data" issue there.  I suppose a feature request here would be to only update the information during an update when the new request is providing data for a future time point.

**Comment by Sudo-Rob** [comment]
Well, I figured that was the case.  Of course, the concern would be if the latest forecast is current, otherwise, it's pretty benign unless it happens at 6 AM or 6 PM (I think).  That could mess up the logic for extracting and assigning forecasts to a weather card.

Other than perhaps keeping an eye on the data, is there anything I should do with the information?

**Comment by MatthewFlamm** [comment]
This library already filters out forecasts whose period ends before the current time.  Note that the HA time is the start time of the period.  So this issue will most impact the twice daily forecasts.  I'm not sure that a user could do much in HA without a ton of complicated templating.  We could handle in the library here as I suggested above by not updating the pynws cached data if the request returns data from a previous update.

**Comment by Sudo-Rob** [comment]
OK.  I'll leave the decision to you.

BTW, I'm trying to address the proper assignment of 6-hour forecasts for the period between midnight and 6 AM.  The obvious thing to do is look at daytime[0] and parse the text into a binary for that interval.  I haven't yet figured out a template. I suppose I should enlist some help from the forum.

**Comment by Sudo-Rob** [comment]
This is a followup.  Here's the response from NOAA NCEP:


"2022-07-01 12:06:23 EDT - Leonardo DaSilvaAdditional comments
Closed Code: Solved (Permanently)
Closed Notes: At 14:09z received closing notes from on-boarding team (John): 

"We have checked our monitoring logs and can confirm we see this behavior where the last forecast is displayed within about an hour of a grid update for specific gridpoints, and is a side effect of our current caching strategy with edge servers. Developers are working on a refactor of the forecast grid service, but this caching strategy has resolved the issue where API was serving stale data that was months old. 

"(LRS)"
