### ISSUE TITLE
oberservation start time parameter fails with tz naive datetime

### ISSUE THREAD

**Issue by MatthewFlamm** [MatthewFlamm/pynws#92]
When passing `start_time=datetime.datetime.utcnow()` to `SimpleNWS.update_observations`, the following error message is returned:

```txt
Invalid date-time \"2023-03-22T11:43:40\", expected format YYYY-MM-DDThh:mm:ssZ or YYYY-MM-DDThh:mm:ss+hh:mm
```

**Comment by MatthewFlamm** [comment]
This could be that a naive datetime was supplied.  If so, this could be handled in a better way in `pynws`.

If a naive datetime is supplied we could either warn or raise an error.

**Comment by kamiyo** [comment]
Apparently, python's `datetime.utcnow()` violates the ISO spec (doesn't include Z). Possible solution is to use `datetime.now(timezone.utc).isoformat()`.

**Comment by MatthewFlamm** [comment]
I had originally used `datetime.utcnow()` in my first attempt in the homeassistant component, as you pointed out this doesn't work.  I _think_ that `datetime.now(timezone.utc).isoformat()` should work. I've started work at https://github.com/MatthewFlamm/home-assistant/tree/nws-start-time.

The issue for this package is that we need to give users a good error message or force the datetime to be aware (probably in utc?) and then warn.  I'm leaning towards raising an error in this package rather than allowing a malformed request be sent to NWS.

**Comment by kamiyo** [comment]
I don't know the datetime object that well and can't test now, but from docs it seems `utcnow()` sets `datetime.tzinfo = None`. Maybe we can just check for that?
